"""add_user_email_to_bets

Revision ID: a16b83bb5aae
Revises: 25185e4a470b
Create Date: 2026-05-31 13:24:50.447132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16b83bb5aae'
down_revision: Union[str, Sequence[str], None] = '25185e4a470b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('user_email', sa.String(), nullable=False))
    op.create_index(op.f('ix_bets_user_email'), 'bets', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_user_email'), table_name='bets')
    op.drop_column('bets', 'user_email')
    # ### end Alembic commands ###
